# Page settings

baseURL = "https://infallible-golick-d59dc1.netlify.com/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#googleAnalytics = "UA-XXXXXXX-Y"

[author]
  name = "Mark Druffel"
  
[params]
    #author = "CowboySmall"
    #description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"

    primaryColor = "#000000" #Propeller headers = #C08A5F
    textPrimaryColor = "#525252"

    [params.profile]
        enable = true
        name = "Mark Druffel"
        tagline = "Consultant"
        avatar = "my_photo_circle.jpg"

    [params.contact]
        enable = true
        location = "Portland, OR"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "mark.druffel@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "www.mark-druffel.com"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Competencies"
        [[params.skills.list.items]]
        details = "Data Strategy"
        [[params.skills.list.items]]
        details = "Requirements Gathering"
        [[params.skills.list.items]]
        details = "Information Architecture"
        [[params.skills.list.items]]
        details = "Data Engineering"
        [[params.skills.list.items]]
        details = "Analysis"
        [[params.skills.list.items]]
        details = "Modeling"
        [[params.skills.list.items]]
        details = "Data Visualisation"
        [[params.skills.list.items]]
        details = "Change Management"
        [[params.skills.list.items]]
        details = "Communication"

        [[params.skills.list]]
        title = "Tools"
        [[params.skills.list.items]]
        details = "R, SQL, HTML, CSS, Python, Cypher"
        [[params.skills.list.items]]
        details = "Tableau, PowerBI, Looker"
        [[params.skills.list.items]]
        details = "AWS, Hugo, Apache Airflow, Shiny Server"
        [[params.skills.list.items]]
        details = "Adobe CS, Gimp, Scribus"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Master of Science in Business Analytics"
        university = "Notre Dame"
        dates = "2016"
        [[params.education.list]]
        degree = "Bachelor of Business Administration"
        university = "Ohio University"
        dates = "2010"

    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"

    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Spanish"
        level = "Professional"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Rock Climbing"
        [[params.interests.list]]
        name = "Hiking"
        [[params.interests.list]]
        name = "Traveling"
        [[params.interests.list]]
        name = "Food / Beer"
        [[params.interests.list]]
        name = "Board / Video Games"

    [params.summary]
        enable = true
        text = "Data science generalist and experienced team builder with a track record of success working with all levels of the organization. Business background with significant development experience in R, SQL, & others, as well as an exceptional ability to communicate complex concepts to a wide range of audiences. Always seeking opportunities to innovate or use new technologies while keeping user experience and business problems front and center."
        
    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Consultant"
        dates = "2017 - Present"
        company = "Propeller"
        details = "Partner with clients to help them execute strategic initiatives and large-scale organizational efforts. Typical engagement includes working with the client to develop a vision and structure for the team, as well as an implementation plan . Execute in any of the following roles for client teams:"
        [[params.experience.list.items]]
        details = "**Analytics:** Data Analyst, Data Scientist"
        [[params.experience.list.items]]
        details = "**Engineering:** Dashboard Developer, Data Engineer"
        [[params.experience.list.items]]
        details = "**Strategy:** Business Analyst, Data Strategist"
        [[params.experience.list.items]]
        details = "**Program:** Change Manager, Project Manager"

        [[params.experience.list]]
        title = "Manager of Reporting"
        dates = "2013 - 2016"
        company = "Northern Trust Hege Fund Services"
        details = "Managed a global team of analysts responsible for data and access products for the platform. Our team managed operations for active clients, implementations for new clients, and product ownership for our services. Core responsibilities:"
        [[params.experience.list.items]]
        details = "Designed, tested, and maintained client & internal reporting"
        [[params.experience.list.items]]
        details = "Performed requirements gathering, design, testing, and deployment of app & data-model development"
        [[params.experience.list.items]]
        details = "Developed product visions and managed the backlogs"
        [[params.experience.list.items]]
        details = "Performed product data analytics to inform product ownership"
        [[params.experience.list.items]]
        details = "Developed prototype tools in collaboration with development teams"
        [[params.experience.list.items]]
        details = "Configured services for new clients"
        [[params.experience.list.items]]
        details = "Managed permissions frameworks for the various client types"

        [[params.experience.list]]
        title = "Senior Consultant"
        dates = "2011 - 2013"
        company = "Plante Moran"
        details = "Managed IT audits and risk assessments with teams of staff auditors. Primarily performed SOC audits and readiness assessments."

        [[params.experience.list]]
        title = "Staff Auditor"
        dates = "2010 - 2011"
        company = "Fifth Third Bank"
        details = "Executed financial and IT audits, as well as risk assessments within several departments of the bank."

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Product Data Information Architecture Alignment"
        meta = "Fortune 100 Sportwear Company"
        tagline = "Developed a data strategy to resolve architecture & process design issues between multiple business units. Conducted ~250 stakeholder interviews to understand and document existing processes & data models. Determined that one customer-facing data entity was used by dozens of business units to accomplish opposing objectives. Corroborated the findings by analyzing product data across the systems used by the business units. Gathered use cases to and built storyboards to illustrate the problem statement with the example products. Leveraged domain driven design to develop an architectural proposal that would enable the business units to manage their data separately, but still maintain the necessary level of collaboration across the business units."

        [[params.projects.list]]
        title = "Organizational Metric Design & Implementation"
        meta = "Nonprofit Healthcare Company"
        tagline = "Designed and implemented organization metrics for an IT DevOps organization. Interviewed IT teams and analyzed data to provide a readiness assessment and proposed data collection processes that would enable more insightful KPIs. Management launched a small program in response to the assessment in order to improve data quality.  Developed an MVP API that integrated disparate systems data in order to enable manage to leverage alternative metrics in the short-term. developed interactive dashboards. Trained the teams and leadership their KPIs for discussion. Documented the process and facilitated training for an operational team to take ownership of the project."  
        

        [[params.projects.list]]
        title = "Legacy BI Product Analysis"
        meta = "Northern Trust"
        tagline = "Informed budget and development prioritization by analyzing and communicating findings regarding technical and process debt associated with the legacy reporting platform. Developed stored procedures that normalized and persisted log & configuration data from the reporting platform and tracked resourcing data across various projects throughout the year. Used the data collected to outline system inefficiencies, workflow inefficiencies, process risks, and low ROI client commitments. The report led to the Executive Leadership team funding a new development team to build a next generation reporting application."
        
        [[params.projects.list]]
        title = "Data Pipeline Development"
        meta = "Services Firm"
        tagline = "Developed a data pipepline to ETL data from cloud software into a multi-layered data lake using several AWS services, R, Python, & Apache-Airflow."

        [[params.projects.list]]
        title = "harvestR"
        meta = "Open Source"
        tagline = "Developed an open source API wrapper for the time tracking software, Harvest. Built to enable dynamic reporting to be built directly off of the system and to simplify extracting data to the data lake."

    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/mark-druffel"
        title = "mark-druffel"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/markdruffel"
        title = "markdruffel"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/MarkDruffel"
        title = "@MarkDruffel"


[params.footer]
    copyright = ""


